# Generated by Django 5.0.3 on 2024-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fn',
            new_name='Firstname',
        ),
        migrations.AddField(
            model_name='employee',
            name='Lastname',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
