# Generated by Django 5.0.3 on 2024-12-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_fn_employee_firstname_employee_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hiredate',
            field=models.DateField(),
        ),
    ]
